### ISSUE TITLE
Error when creating MSSQL Dbase

### ISSUE THREAD

**Issue by ryderhaggard** [EVEIPH/EVE-SDE-Database-Builder#23]
Error Message:

An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: ImportTranslationLanguages
Message: No connection associated with this command
Raw Error Text: System.InvalidOperationException: No connection associated with this command
   at System.Data.SQLite.SQLiteCommand.InitializeForReader()
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EVE_SDE_Database_Builder.SQLiteDB.SelectfromTable(List`1 SelectFieldValues, String SelectTableName, List`1 SelectWhereClause, Boolean& RecordsFound)
   at EVE_SDE_Database_Builder.SQLiteDB.DropTable(String TableName)
   at EVE_SDE_Database_Builder.SQLiteDB.CreateTable(String TableName, List`1 TableStructure)
   at EVE_SDE_Database_Builder.YAMLTranslations.ImportTranslationLanguages(ImportParameters Params, Boolean ImportTable, Boolean ShowProgress)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Database is created, translationColumns table is created, no data is imported and error occurs.

**Comment by Darconica** [comment]
I got different error message when creating MSSQL Dbase

An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: 
Message: Kan een aantal of alle id-verwijzingen niet omzetten.
Raw Error Text: System.Security.Principal.IdentityNotMappedException: Kan een aantal of alle id-verwijzingen niet omzetten.
   bij Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   bij Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   bij Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   bij Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   bij EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   bij EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   bij System.Windows.Forms.Control.OnClick(EventArgs e)
   bij System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bij System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bij System.Windows.Forms.Control.WndProc(Message& m)
   bij System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bij System.Windows.Forms.Button.WndProc(Message& m)
   bij System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Zifrian** [comment]
Thank you both, I pushed a patch to fix a related error. Let me know if this isn't working correctly.

**Comment by Darconica** [comment]
I update to the latest version aviable and I'm still getting the same error on creatien Mssql Dbase.

**Comment by Zifrian** [comment]
> I update to the latest version aviable and I'm still getting the same error on creatien Mssql Dbase.

Can you tell me more? When does this happen? I'm not having any issues with creation. What settings are you using? Thanks

**Comment by Darconica** [comment]
I'm using the default settings and english as language setting. Also I was mistaken it was not during mssql dbase creation but during ms acces dbase creation

**Comment by Zifrian** [comment]
Thanks. I made several bug fixes to translations, and the ms Access DB import is working. Let me know if you still get the error and when. Thanks

**Comment by ryderhaggard** [comment]
Downloaded latest version, deleted the aborted attempt to create the Dbase, and re-ran. got the following error still.

An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: ImportTranslationLanguages
Message: No connection associated with this command
Raw Error Text: System.InvalidOperationException: No connection associated with this command
   at System.Data.SQLite.SQLiteCommand.InitializeForReader()
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EVE_SDE_Database_Builder.SQLiteDB.SelectfromTable(List`1 SelectFieldValues, String SelectTableName, List`1 SelectWhereClause, Boolean& RecordsFound)
   at EVE_SDE_Database_Builder.SQLiteDB.DropTable(String TableName)
   at EVE_SDE_Database_Builder.SQLiteDB.CreateTable(String TableName, List`1 TableStructure)
   at EVE_SDE_Database_Builder.YAMLTranslations.ImportTranslationLanguages(ImportParameters Params, Boolean ImportTable, Boolean ShowProgress)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ryderhaggard** [comment]
Bit more info:

The database is created, the following table is created:
translationColumns 

with the following structure
columnName	nvarchar(128)	Checked
masterID	nvarchar(128)	Checked
tableName	nvarchar(256)	Checked
tcGroupID	smallint	Checked
tcID	smallint	Checked
		Unchecked

No content is populated.

**Comment by Zifrian** [comment]
> Downloaded latest version, deleted the aborted attempt to create the Dbase, and re-ran. got the following error still.
> 
> An Unhandled Exception has occured and the program will now close. Copy the data below and send to developer.
> 
> Source: ImportTranslationLanguages Message: No connection associated with this command Raw Error Text: System.InvalidOperationException: No connection associated with this command at System.Data.SQLite.SQLiteCommand.InitializeForReader() at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) at EVE_SDE_Database_Builder.SQLiteDB.SelectfromTable(List`1 SelectFieldValues, String SelectTableName, List`1 SelectWhereClause, Boolean& RecordsFound) at EVE_SDE_Database_Builder.SQLiteDB.DropTable(String TableName) at EVE_SDE_Database_Builder.SQLiteDB.CreateTable(String TableName, List`1 TableStructure) at EVE_SDE_Database_Builder.YAMLTranslations.ImportTranslationLanguages(ImportParameters Params, Boolean ImportTable, Boolean ShowProgress) at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType) at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e) at System.Windows.Forms.Control.OnClick(EventArgs e) at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) at System.Windows.Forms.Control.WndProc(Message& m) at System.Windows.Forms.ButtonBase.WndProc(Message& m) at System.Windows.Forms.Button.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I've tried several times and options to reproduce this error and I can't get it to pop up. Can you send a screen of the form with the options you are using?

**Comment by Darconica** [comment]
I keep getting errors on ms acces dbase creation.

>An Unhandled Exception has occured and the program will now close.
Copy the data below and send to developer.

Source: 
Message: Some or all identity references could not be translated.
Raw Error Text: System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at EVE_SDE_Database_Builder.frmMain.BuildEVEDatabase(Object UpdateDatabase, DatabaseType DatabaseType)
   at EVE_SDE_Database_Builder.frmMain.btnBuildDatabase_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Zifrian** [comment]
> Some or all identity references could not be translated.

I need more information. Can you post a screenshot? Are you using a username/password for the file?

**Comment by Darconica** [comment]
I added some screenshots.
The last one is the code error that seems to be responcible for the problem. When I run the code in Visual studio 2022.

![Screenshot 2024-08-09 155700](https://github.com/user-attachments/assets/04deddc6-4314-4647-a233-ab663e7b73b1)
![Screenshot 2024-08-09 155950](https://github.com/user-attachments/assets/188987a3-da69-467d-b1f6-a797cf05b05a)
![Screenshot 2024-08-09 160152](https://github.com/user-attachments/assets/9c4e2988-edc1-438d-8121-15c89072027d)

**Comment by Darconica** [comment]
2 more screenshots of the error code according to visual studio 2022
![Screenshot 2024-08-09 161651](https://github.com/user-attachments/assets/795f8aea-691e-4424-8864-176ec5d64bd4)
![Screenshot 2024-08-09 161726](https://github.com/user-attachments/assets/f0deeb39-833c-4f13-a5f1-790c8f7f7ee3)

**Comment by Zifrian** [comment]
@Darconica Thank you so much for this info. I've pushed a patch that I think will correct this issue. Let me know if it works for you now. Thanks

**Comment by Darconica** [comment]
No problem. 
Still not working properly. No code releated errors anymore.
But now getting error related to data format while trying to import data to database.
More specific the data separation char beeing the same used in decimale numbers.
![Screenshot 2024-08-19 095348](https://github.com/user-attachments/assets/0a742503-0971-4f4b-b654-9a1100f8ef20)

**Comment by Zifrian** [comment]
Ok thanks. What is your locality/country? I think these issues are from what version of windows you use. Not an issue but want to test against a known locality setting.

**Comment by Darconica** [comment]
I'm from Belgium
